project:
  type: website

website:
  title: "Massimo Rusconi"
  search: false
  navbar:
    pinned: true
    logo-href: index.qmd#home
    left:
      - href: index.qmd#home
        text: Home
      - href: index.qmd#academic
        text: Academic
      - href: index.qmd#industry
        text: Industry
      - href: index.qmd#skills
        text: Skills & Interests
      - href: index.qmd#cv
        text: CV
      - href: index.qmd#contact
        text: Contact
  page-footer:
    left: "&copy; 2026 Massimo Rusconi"
    right: "[massimo.rusconi@uninsubria.it](mailto:massimo.rusconi@uninsubria.it)"

format:
  html:
    theme:
      light:
        - cosmo
        - brand
      dark:
        - cosmo
        - brand
        - theme-dark.scss
    css: styles.css
    include-before-body: _partials/scientific-background.html
    toc: true
    title-block-style: none
    respect-user-color-scheme: true
